const USER_LOCALSTORAGE_KEY = 'user'
const ARTICLES_VIEW_LOCALSTORAGE_KEY = 'articles_view'
const LOCAL_STORAGE_THEME_KEY = 'theme'

export {
  USER_LOCALSTORAGE_KEY,
  ARTICLES_VIEW_LOCALSTORAGE_KEY,
  LOCAL_STORAGE_THEME_KEY,
}
